### ISSUE TITLE
Support for ERPNext Version-14

### ISSUE THREAD

**Issue by vinodkumarkolli** [yrestom/erpnext_telegram#20]
Hi, 
I am trying to upgrade my Erpnext Version 13 to Version 14. I have this app installed on my Version 13 instance. 
However, when I am trying to upgrade bench command is throwing error that it couldn't find the git reference of erpnext_telegram app for the version 14. 
Did anyone try upgrading to Version 14 and anyone find a solution?

Thanks & Regards,
Vinod Kumar K

**Comment by Alababdiy** [comment]
it’s working for erpnext-v14

**Comment by yrestom** [comment]
It's working now
