### ISSUE TITLE
Notifications are not working since few days

### ISSUE THREAD

**Issue by moizsami** [yrestom/erpnext_telegram#25]
Suddenly the notifications have stopped working, I am using frappe cloud hosted ERPNext and have installed Telegram Notifications, everything was working smoothly and suddenly this happened.
When I try to add a new user in telegram user settings, I cannot save the record even, i think the chat id is not updating as well.

**Comment by yrestom** [comment]
Please share APPs version and any error log

**Comment by moizsami** [comment]
> 

I am using version 13 and since im using the cloud version hosted by frappe am not able to get hold on logs.

**Comment by yrestom** [comment]
And check if there is any error in Browser's console

**Comment by moizsami** [comment]
> Please share the specific version numbers of Frappe, Erpnext, and Telegram app

ERPNext: v13.42.7
Erpnext Telegram Integration: v1.0.1 
Frappe Framework: v13.46.3

**Comment by moizsami** [comment]
> Erpnext Telegram Integration has a new version 1.1.0 can you update it?

Can you please post it on Marketplace, as since im using cloud version I can only install apps which are there on the market place, I have one instance I just installed last week, even that one is having version 1.0.1 as I downloaded it from marketplace

**Comment by yrestom** [comment]
The new version is waiting for approval there, you can open a support ticket there to ask bout it

**Comment by moizsami** [comment]
> The new version is waiting for approval there, you can open a support ticket there to ask bout it

Thanks alot for helping me out here, sure I will ask there. Hopefully the issue should be resolved with the new version right ?

**Comment by moizsami** [comment]
> The new version is waiting for approval there, you can open a support ticket there to ask bout it

Hi Yousef, telegram application has been updated on Frappe Cloud, I can see in about section as well that version is updated to 1.1.0 now.  still I am facing the same issue with notifications. Actually I cannot get the Chat ID also, for testing purposes I deleted few users and trying to add them backm When I click on the Get Chat ID button nothing happens. 

Can you please assist in what might be the issue ?

Thanks

**Comment by moizsami** [comment]
I was able to get hold of a particular error pop up which appeared, please find it below:
`### App Versions
```
{
	"chat": "0.0.1",
	"erpnext": "13.43.0",
	"erpnext_telegram_integration": "1.1.0",
	"frappe": "13.46.4"
}
```
### Route
```
Form/Telegram User Settings/new-telegram-user-settings-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/erpnext_telegram_integration/erpnext_telegram_integration/erpnext_telegram_integration/doctype/telegram_user_settings/telegram_user_settings.py", line 52, in get_chat_id_button
    for u in updates:
TypeError: 'coroutine' object is not iterable

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"telegram_token": "f639c378c9504a6bbeb2b365a2bc7dda8ce5cb4b",
		"telegram_settings": "RajBakers"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext_telegram_integration.erpnext_telegram_integration.doctype.telegram_user_settings.telegram_user_settings.get_chat_id_button"
}
```
### Response Data
```
{
	"exception": "TypeError: 'coroutine' object is not iterable"
}
````

**Comment by moizsami** [comment]
Hi, any suggestions how this can be resolved? would really appreciate it.

**Comment by yrestom** [comment]
@moizsami I will work on it next week

**Comment by moizsami** [comment]
> @moizsami I will work on it next week

@yrestom  Thank you :)
let me know if you need me for testing or any other stuff.

**Comment by moizsami** [comment]
@yrestom  Thanks alot really, I assume it should be again waiting for approval with the Frappe cloud team right? should I contact them to approve the update ?

**Comment by yrestom** [comment]
> @yrestom Thanks alot really, I assume it should be again waiting for approval with the Frappe cloud team right? should I contact them to approve the update ?

Yes
